#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif

// qmk json2c keymap.json > keymap.c
// keymap.json from https://github.com/splitkb/qmk_userspace
/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x6_5_hlc(KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC, MT(MOD_LCTL, KC_ESC), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, MT(MOD_RCTL, KC_QUOTE), KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_LBRC, KC_CAPS, MO(5), KC_RBRC, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, MO(6), KC_LGUI, MT(MOD_LALT, KC_ENT), KC_SPC, MO(3), MO(4), KC_SPC, KC_RALT, KC_RGUI, KC_APP, KC_MUTE, KC_NO, KC_NO, KC_NO, KC_NO, KC_MUTE, KC_NO, KC_NO, KC_NO, KC_NO),
    [1] = LAYOUT_split_3x6_5_hlc(KC_TAB, KC_QUOTE, KC_COMM, KC_DOT, KC_P, KC_Y, KC_F, KC_G, KC_C, KC_R, KC_L, KC_BSPC, MT(MOD_LCTL, KC_ESC), KC_A, KC_O, KC_E, KC_U, KC_I, KC_D, KC_H, KC_T, KC_N, KC_S, MT(MOD_RCTL, KC_MINUS), KC_LSFT, KC_SCLN, KC_Q, KC_J, KC_K, KC_X, KC_LBRC, KC_CAPS, MO(5), KC_RBRC, KC_B, KC_M, KC_W, KC_V, KC_Z, KC_RSFT, MO(6), KC_LGUI, MT(MOD_LALT, KC_ENT), KC_SPC, MO(3), MO(4), KC_SPC, KC_RALT, KC_RGUI, KC_APP, KC_MUTE, KC_NO, KC_NO, KC_NO, KC_NO, KC_MUTE, KC_NO, KC_NO, KC_NO, KC_NO),
    [2] = LAYOUT_split_3x6_5_hlc(KC_TAB, KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_BSPC, MT(MOD_LCTL, KC_ESC), KC_A, KC_R, KC_S, KC_T, KC_G, KC_M, KC_N, KC_E, KC_I, KC_O, MT(MOD_RCTL, KC_QUOTE), KC_LSFT, KC_Z, KC_X, KC_C, KC_D, KC_V, KC_LBRC, KC_CAPS, MO(5), KC_RBRC, KC_K, KC_H, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, MO(6), KC_LGUI, MT(MOD_LALT, KC_ENT), KC_SPC, MO(3), MO(4), KC_SPC, KC_RALT, KC_RGUI, KC_APP, KC_MUTE, KC_NO, KC_NO, KC_NO, KC_NO, KC_MUTE, KC_NO, KC_NO, KC_NO, KC_NO),
    [3] = LAYOUT_split_3x6_5_hlc(_______, _______, _______, _______, _______, _______, KC_PGUP, KC_HOME, KC_UP, KC_END, KC_VOLU, KC_DEL, _______, KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, _______, KC_PGDN, KC_LEFT, KC_DOWN, KC_RGHT, KC_VOLD, KC_INS, _______, _______, _______, _______, _______, _______, _______, KC_SCRL, _______, _______, KC_PAUSE, KC_MPRV, KC_MPLY, KC_MNXT, KC_MUTE, KC_PSCR, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______),
    [4] = LAYOUT_split_3x6_5_hlc(KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_EQL, KC_TILD, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_PLUS, KC_PIPE, KC_BSLS, KC_COLN, KC_SCLN, KC_MINS, KC_LBRC, KC_LCBR, _______, _______, KC_RCBR, KC_RBRC, KC_UNDS, KC_COMM, KC_DOT, KC_SLSH, KC_QUES, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______),
    [5] = LAYOUT_split_3x6_5_hlc(_______, KC_F9, KC_F10, KC_F11, KC_F12, _______, _______, _______, _______, _______, _______, _______, _______, KC_F5, KC_F6, KC_F7, KC_F8, _______, _______, KC_RSFT, KC_RCTL, KC_LALT, KC_RGUI, _______, _______, KC_F1, KC_F2, KC_F3, KC_F4, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______),
    [6] = LAYOUT_split_3x6_5_hlc(_______, _______, _______, DF(0), _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, DF(1), _______, _______, RM_TOGG, RM_SATU, RM_HUEU, RM_VALU, RM_NEXT, _______, _______, _______, _______, DF(2), _______, _______, _______, _______, _______, _______, _______, RM_SATD, RM_HUED, RM_VALD, RM_PREV, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______)
};
#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [0] = {ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_PGUP, KC_PGDN), ENCODER_CCW_CW(KC_PGUP, KC_PGDN)},
    [1] = {ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_PGUP, KC_PGDN), ENCODER_CCW_CW(KC_PGUP, KC_PGDN)},
    [2] = {ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_PGUP, KC_PGDN), ENCODER_CCW_CW(KC_PGUP, KC_PGDN)},
    [3] = {ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_PGUP, KC_PGDN), ENCODER_CCW_CW(KC_PGUP, KC_PGDN)},
    [4] = {ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_PGUP, KC_PGDN), ENCODER_CCW_CW(KC_PGUP, KC_PGDN)},
    [5] = {ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_PGUP, KC_PGDN), ENCODER_CCW_CW(KC_PGUP, KC_PGDN)},
    [6] = {ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_PGUP, KC_PGDN), ENCODER_CCW_CW(KC_PGUP, KC_PGDN)}
};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)


#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

#define C_ALT_REPEAT_KEY KC_KP_1

// Indicators without RGB Matrix Effect ​
// If you want to just use RGB indicators without RGB matrix effect, it is not possible to disable the latter because toggling RGB off will disable everything. You can workaround it with solid effect and colors off using this init function:
void keyboard_post_init_user(void) {
    rgb_matrix_enable();
    rgb_matrix_mode_noeeprom(RGB_MATRIX_SOLID_COLOR);
    rgb_matrix_sethsv_noeeprom(HSV_OFF);
}

// void set_layer_color(uint8_t r, uint8_t g, uint8_t b) {
//   for (int i = 0; i < RGB_MATRIX_LED_COUNT; i++) {
//     rgb_matrix_set_color( i, r, g, b);
//   }
// }

// LEDs 0-5 are under glow
// LED 6 is lower outer thumb key
bool rgb_matrix_indicators_user(void) {
  switch (biton32(layer_state)) {
// layer_state_t layer_state_set_user(layer_state_t state) {
//     switch (get_highest_layer(state)) {
    case 2:
        if (is_keyboard_master())
        {
            rgb_matrix_set_color(14, RGB_GREEN);
            rgb_matrix_set_color(15, RGB_GREEN);
            rgb_matrix_set_color(20, RGB_GREEN);
            rgb_matrix_set_color(21, RGB_GREEN);
            rgb_matrix_set_color(26, RGB_GREEN);
            rgb_matrix_set_color(27, RGB_GREEN);
        }
        else
        {
            rgb_matrix_set_color(8, RGB_YELLOW);
            rgb_matrix_set_color(14, RGB_YELLOW);
            rgb_matrix_set_color(15, RGB_YELLOW);
            rgb_matrix_set_color(16, RGB_YELLOW);
            rgb_matrix_set_color(20, RGB_YELLOW);
            rgb_matrix_set_color(21, RGB_YELLOW);
            rgb_matrix_set_color(22, RGB_YELLOW);
            rgb_matrix_set_color(26, RGB_YELLOW);
            rgb_matrix_set_color(27, RGB_YELLOW);
            rgb_matrix_set_color(28, RGB_YELLOW);
        }
      break;
    case 3:
    //   set_layer_color(RGB_YELLOW);
        if (is_keyboard_master())
        {
            rgb_matrix_set_color(14, RGB_BLUE);
            rgb_matrix_set_color(15, RGB_BLUE);
            rgb_matrix_set_color(16, RGB_BLUE);
            rgb_matrix_set_color(17, RGB_YELLOW);
            rgb_matrix_set_color(20, RGB_YELLOW);
            rgb_matrix_set_color(21, RGB_YELLOW);
            rgb_matrix_set_color(22, RGB_YELLOW);
            rgb_matrix_set_color(23, RGB_BLUE);
            rgb_matrix_set_color(26, RGB_YELLOW);
            rgb_matrix_set_color(27, RGB_YELLOW);
            rgb_matrix_set_color(28, RGB_YELLOW);
            rgb_matrix_set_color(29, RGB_YELLOW);
        }
        else
        {            
            rgb_matrix_set_color(20, RGB_ORANGE);
            rgb_matrix_set_color(21, RGB_ORANGE);
            rgb_matrix_set_color(22, RGB_ORANGE);
            rgb_matrix_set_color(27, RGB_ORANGE);
        }
      break;
    case 4:
        if (is_keyboard_master())
        {
            rgb_matrix_set_color(6, RGB_ORANGE);
            rgb_matrix_set_color(7, RGB_ORANGE);
            rgb_matrix_set_color(20, RGB_YELLOW);
            rgb_matrix_set_color(25, RGB_GREEN);
            rgb_matrix_set_color(26, RGB_GREEN);
            rgb_matrix_set_color(28, RGB_GREEN);
        }
        else
        {            
        }
      break;
    case 7:
        if (is_keyboard_master())
        {
        }
        else
        { 
            rgb_matrix_set_color(15, RGB_ORANGE);
            rgb_matrix_set_color(21, RGB_ORANGE);
            rgb_matrix_set_color(27, RGB_ORANGE);           

            rgb_matrix_set_color(17, RGB_ORANGE);
            rgb_matrix_set_color(23, RGB_ORANGE);
            rgb_matrix_set_color(29, RGB_ORANGE);

            rgb_matrix_set_color(18, RGB_GREEN);
            rgb_matrix_set_color(24, RGB_GREEN);
            rgb_matrix_set_color(30, RGB_GREEN);
        }
      break;  
   default:
    rgb_matrix_set_color_all(0, 0, 0);
    break;
  }
  return true;
}

enum custom_keycodes {
    M_PPY = SAFE_RANGE,
};

uint16_t get_alt_repeat_key_keycode_user(uint16_t keycode, uint8_t mods) {
    bool cmd = (mods & MOD_MASK_GUI); 

    switch (keycode) {
        case KC_P: return M_PPY;
        case LALT_T(KC_S): return KC_C;
        case KC_O: return KC_A;
        case KC_C: 
            if (cmd) {
                return LGUI(KC_V);
            }
            else {
                return KC_S;
            }
            break;
        case KC_X: 
            if (cmd) {
                return LGUI(KC_V);
            }
            break;

        // TODO: use get_repeat_key_count() to increment for each press
        case KC_0: return KC_1;
        case KC_1: return KC_2;
        case KC_2: return KC_3;
        case KC_3: return KC_4;
        case KC_4: return KC_5;
        case RALT_T(KC_4): return KC_5;
        case KC_5: return KC_6;
        case RGUI_T(KC_5): return KC_6;
        case KC_6: return KC_7;
        case RCTL_T(KC_6): return KC_7;
        case KC_7: return KC_8;
        case KC_8: return KC_9;
        case KC_9: return KC_0;
    }

    return KC_TRNS;
}

bool process_custom_alt_repeat_key(int prev_keycode, int prev_mods) {
    switch (prev_keycode) {
        case KC_B:
            SEND_STRING("ecause");
            return false;
        case KC_SEMICOLON:
            send_char(')');
            return false;
        case KC_C:
            send_char('#');
            return false;
    }

    return true;
}

bool process_record_user(uint16_t keycode, keyrecord_t* record) {
    switch (keycode) {
        case C_ALT_REPEAT_KEY:
            if (record->event.pressed) {
               return process_custom_alt_repeat_key(get_last_keycode(), get_last_mods()); 
            }

            return true;
        case M_PPY:
            if (get_repeat_key_count() == -1)
            {
                if (record->event.pressed) {
                    SEND_STRING(/*p*/"py");
                }
            }

            return false;
    }

    return true;
}

// Ignore backspace, nav keys etc for alt repeat. So cmd c, repeat triggers cmd v even after switching to another tab/app
bool remember_last_key_user(uint16_t keycode, keyrecord_t* record, uint8_t* remembered_mods) {
    switch (keycode) {
        case KC_BSPC:
        case KC_DEL:
        case KC_LEFT:
        case KC_RIGHT:
        case KC_UP:
        case KC_DOWN:
        case KC_HOME:
        case KC_END:
        case KC_PGUP:
        case KC_PGDN:
        case KC_TAB:
        case KC_ENTER:
        case KC_SPC:
        case LSFT_T(KC_BSPC):
        case RALT_T(KC_LEFT):
        case RGUI_T(KC_DOWN):
        case RCTL_T(KC_RIGHT):
        case LT(2, KC_TAB):
        case LT(3, KC_SPC):
        case C_ALT_REPEAT_KEY:
            return false;
    }

    return true;
}
